<a href="https://colab.research.google.com/github/imranttsia/Data-visualization/blob/main/numpy_application_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
#what numpy has, it can be checked as below
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [4]:
np.__version__

'1.22.4'

In [5]:
!pip install --upgrade numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 99.1 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.3 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.3 which is incompatible.


Scalar

In [6]:
a=50
print(type(a))
a=np.array(50)
print(type(a))

<class 'int'>
<class 'numpy.ndarray'>


In [8]:
a=np.array(50)
print(a)
print(type(a))
print(a.ndim)#dimension
print(a.size)#size
# since dimension is zero it is scalar and one element which is size

50
<class 'numpy.ndarray'>
0
1


Vector

In [10]:
a = np.array([1,7,9,9,20])

print(a)
print(type(a))
print(a.ndim)# 1 dimension
print(a.size)# 5 elements

[ 1  7  9  9 20]
<class 'numpy.ndarray'>
1
5


Matrix

In [11]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])


display(a)
display(type(a))
display(a.ndim)# 2
display(a.size)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

numpy.ndarray

2

9

python list vs numpy array

In [12]:
%%time
display([i+5 for  i in range(1,1000000)])

[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


CPU times: user 57.9 ms, sys: 11.2 ms, total: 69.1 ms
Wall time: 72.8 ms


In [13]:
%%time
np.arange(1,1000000) + 5

CPU times: user 5.46 ms, sys: 938 µs, total: 6.4 ms
Wall time: 9.4 ms


array([      6,       7,       8, ..., 1000002, 1000003, 1000004])

In [14]:
26/161*100

16.149068322981368

Easy to use

In [15]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

display(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
for row in a:
  print(row)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [19]:
for ridx,_ in enumerate(a):
  print (ridx)

0
1
2


In [22]:
for ridx,_ in enumerate(a):
    for cidx,_ in enumerate(a[ridx]):
     print(ridx,cidx, sep=",")
#ridx is row index
#cidx is coloumn index

0,0
0,1
0,2
1,0
1,1
1,2
2,0
2,1
2,2


In [21]:
for ridx,_ in enumerate(a):
    for cidx,_ in enumerate(a[ridx]):
#         print(ridx,cidx, sep=",")
        a[ridx][cidx] += 5
    
a   

[[6, 7, 8], [9, 10, 11], [12, 13, 14]]

In [23]:
a = np.array([[1,2,3],
    [4,5,6],
    [7,8,9]])

a + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [24]:
#rows, columns
a.shape

(3, 3)

Now apply some code with offical documentation

In [25]:
a = np.arange(1,11)
display(a)
#num of elements
print(a.shape)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

(10,)


In [26]:
a = np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [27]:
a.shape
#slide,row,columns

(3, 3, 3)

In [28]:
a = np.arange(4*5*3).reshape(4,5,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [29]:
a.shape


(4, 5, 3)

What is the difference between a list and an array?
List is used to collect items that usually consist of elements of multiple data types. An array is also a vital component that collects several items of the same data type. List cannot manage arithmetic operations. Array can manage arithmetic operations.

In [30]:
a[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [31]:
a[1]

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [32]:
a[-1]

array([[45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [33]:
a[-2]

array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [34]:
print(a[0])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


How to create a basic array

In [35]:
a = np.array([1,2,23,3,5])
print(type(a))

<class 'numpy.ndarray'>


In [36]:
a = np.zeros((10,10))
print(type(a))
a

<class 'numpy.ndarray'>


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
a = np.ones((10,10))
print(type(a))
a

<class 'numpy.ndarray'>


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
a = np.empty((10,10))
print(type(a))
a
# Empty function gives garbage value 

<class 'numpy.ndarray'>


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Linspace

In [41]:
a = np.linspace(1,2,5)
print(len(a))
a
#1 is starting value, 2 is final value and 5 is the steps in between 1 and 2

5


array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [42]:
np.arange(4)

array([0, 1, 2, 3])

In [43]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [44]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [45]:
a = np.ones((2,3))
print(a.dtype)
a

float64


array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
a = np.ones((2,3),dtype=np.int64)
print(a.dtype)
a

int64


array([[1, 1, 1],
       [1, 1, 1]])

In [47]:
a = np.ones((2,3),dtype=str)
print(a.dtype)
a

<U1


array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

Sorting

In [48]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort()

In [49]:
a = np.random.randint(1,100, size=(10,10))
a

array([[12, 50, 94,  9, 25, 83, 20, 94, 49, 75],
       [63, 39,  7, 81, 65, 17, 13, 68, 49, 44],
       [14, 95, 27, 98, 43, 54, 76, 20, 40,  3],
       [11,  3, 38, 14, 39, 85, 52, 21, 17, 84],
       [ 5, 57, 67, 28, 25, 86, 90, 56, 92, 90],
       [25, 64, 34,  3, 21, 78, 36, 53, 96,  8],
       [86, 71, 70, 23, 10, 45, 63, 80,  8, 42],
       [11, 10, 44, 31, 87, 79, 31, 81, 58, 96],
       [ 3, 58,  3, 96, 97, 23,  5, 82, 11, 40],
       [29,  8, 26,  6, 51, 50, 69, 45, 95, 71]])

In [50]:
np.sort(a, axis=-1)
# According to column

array([[ 9, 12, 20, 25, 49, 50, 75, 83, 94, 94],
       [ 7, 13, 17, 39, 44, 49, 63, 65, 68, 81],
       [ 3, 14, 20, 27, 40, 43, 54, 76, 95, 98],
       [ 3, 11, 14, 17, 21, 38, 39, 52, 84, 85],
       [ 5, 25, 28, 56, 57, 67, 86, 90, 90, 92],
       [ 3,  8, 21, 25, 34, 36, 53, 64, 78, 96],
       [ 8, 10, 23, 42, 45, 63, 70, 71, 80, 86],
       [10, 11, 31, 31, 44, 58, 79, 81, 87, 96],
       [ 3,  3,  5, 11, 23, 40, 58, 82, 96, 97],
       [ 6,  8, 26, 29, 45, 50, 51, 69, 71, 95]])

In [51]:
np.sort(a, axis=0)
# According to row

array([[ 3,  3,  3,  3, 10, 17,  5, 20,  8,  3],
       [ 5,  8,  7,  6, 21, 23, 13, 21, 11,  8],
       [11, 10, 26,  9, 25, 45, 20, 45, 17, 40],
       [11, 39, 27, 14, 25, 50, 31, 53, 40, 42],
       [12, 50, 34, 23, 39, 54, 36, 56, 49, 44],
       [14, 57, 38, 28, 43, 78, 52, 68, 49, 71],
       [25, 58, 44, 31, 51, 79, 63, 80, 58, 75],
       [29, 64, 67, 81, 65, 83, 69, 81, 92, 84],
       [63, 71, 70, 96, 87, 85, 76, 82, 95, 90],
       [86, 95, 94, 98, 97, 86, 90, 94, 96, 96]])

In [52]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [54]:
np.argsort(arr)
#  0  1  2  3  4  5  6  7
# [2, 1, 5, 3, 7, 4, 6, 8]

array([1, 0, 3, 5, 2, 6, 4, 7])