<a href="https://colab.research.google.com/github/imranttsia/Data-visualization/blob/main/pandas_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas

*   Series
*   Pandas

In [1]:
l1 = ['a','b','c','d']
display(l1)
display(type(l1))

['a', 'b', 'c', 'd']

list

In [2]:
import pandas as pd


In [3]:
# list

l1 = ['a','b','c','d']
display(l1)
display(type(l1))
print('============')
s1 = pd.Series(l1)
display(s1)
display(type(s1))

['a', 'b', 'c', 'd']

list

0    a
1    b
2    c
3    d
dtype: object

pandas.core.series.Series

In [4]:
s1

0    a
1    b
2    c
3    d
dtype: object

In [5]:
s2 = pd.Series([1,2,3,5])
s2

0    1
1    2
2    3
3    5
dtype: int64

In [6]:
l1


['a', 'b', 'c', 'd']

In [7]:
# tuple
t1 = (1,7,8,9,10.2,78)
s1 = pd.Series(t1)

display(s1)
display(type(s1))

0     1.0
1     7.0
2     8.0
3     9.0
4    10.2
5    78.0
dtype: float64

pandas.core.series.Series

In [8]:
# Dictionary
d1 = {
    'a':1,
    'b': 'pakistan',
    'c':20,
    'd':100
}

s1 = pd.Series(d1)
s1

a           1
b    pakistan
c          20
d         100
dtype: object

In [9]:
k = ['a','b','c']
v = [100,200,300]


s1 = pd.Series(data=v, index=k)
display(s1)
s1 = pd.Series(v,k)
display(s1)

a    100
b    200
c    300
dtype: int64

a    100
b    200
c    300
dtype: int64

In [10]:
s2 = pd.Series([1,2,3,5], name='rollnumber')
s2

0    1
1    2
2    3
3    5
Name: rollnumber, dtype: int64

In [11]:
display(s2.index)
display(s2.values)
display(s2.name)

RangeIndex(start=0, stop=4, step=1)

array([1, 2, 3, 5])

'rollnumber'

In [12]:
dir(s2)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__redu

create series 
* list
* tuple
* dictionary
* key,value pass in index and value argument

DataFrame

In [13]:
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]

display(data)
print(type(data))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

<class 'list'>


In [14]:
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]

df = pd.DataFrame(data) # list of list
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [15]:
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]

df = pd.DataFrame(data,
                  columns = ['id','name','course']) # list of list
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


id  name  course
0   1     2       3
1   4     5       6
2   7     8       9

In [16]:
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]

df = pd.DataFrame(data,
                  columns = ['id','name','course'],
                 index=['a','b','c']) # list of list
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


id  name  course
a   1     2       3
b   4     5       6
c   7     8       9

In [17]:
data = ((1,2,3),
       (4,5,6),
       (7,8,9))

df = pd.DataFrame(data) # list of list
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [18]:
import numpy as np

data = np.random.randint(1,100, size=(10,10))
data

array([[94, 76, 87, 82, 10, 83, 47, 43, 21, 92],
       [46, 62, 32, 65,  8, 39, 35, 95, 61, 34],
       [50, 14, 59, 76, 72,  9, 84, 26, 42,  7],
       [38, 65, 70, 76, 47, 76, 35, 88, 43,  6],
       [25, 34, 96, 95, 46, 36, 20, 90, 75, 35],
       [27, 26, 11, 77, 27, 34, 49,  6,  9, 16],
       [69, 55, 55, 99, 14, 91, 11,  2, 66, 36],
       [84, 79, 90, 75, 77, 83, 63, 31, 53, 74],
       [67, 24, 22, 11, 12, 19, 24, 43, 41, 24],
       [79, 55, 45, 72, 62, 51, 93, 31, 97, 74]])

In [19]:
data = np.random.randint(1,100, size=(10,10))

df = pd.DataFrame(data)
df

0   1   2   3   4   5   6   7   8   9
0  31  86  79   9   1  99  72  42  10  95
1  51  58  45  66  65  38  74  58  62  88
2  13  39  53  14  90  15  49   6   1  29
3  66  67  85  76  53  41  30  26  49  12
4  71  69   3  27  85  81   7  85  18  51
5  84  91   4  37  11  86   8  90  28  27
6  47  66  58  35   5  94  33   7  23  21
7  16  11  39   4  84  15   6  63  70   1
8  15  78  66  45   2  79  34  23  24  14
9  21  28  30  31   9  98  43  81  74  99

create dataframe with dictionary

In [20]:
d1 = {
    "id":[1,2,3],
    "name":['Hamza',"Asif",'Junaid'],
    'NED course':['AI',"DataVisualization",'DS']
}
display(d1)

df = pd.DataFrame(d1)
df

{'id': [1, 2, 3],
 'name': ['Hamza', 'Asif', 'Junaid'],
 'NED course': ['AI', 'DataVisualization', 'DS']}

id    name         NED course
0   1   Hamza                 AI
1   2    Asif  DataVisualization
2   3  Junaid                 DS

extract columns from dataframe


dataframe.column_name
  
  space not allowed in column name
  
  we can't add new column

dataframe['column name']

In [21]:
display(df)
print(type(df))
sid = df.id

print(type(sid), )
sid

id    name         NED course
0   1   Hamza                 AI
1   2    Asif  DataVisualization
2   3  Junaid                 DS

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


0    1
1    2
2    3
Name: id, dtype: int64

In [22]:
display(df)

sname = df.name

sname

id    name         NED course
0   1   Hamza                 AI
1   2    Asif  DataVisualization
2   3  Junaid                 DS

0     Hamza
1      Asif
2    Junaid
Name: name, dtype: object

In [23]:
display(df)

scourse = df.NED course
scourse

SyntaxError: ignored

In [24]:
display(df)

scourse = df['NED course']
scourse

id    name         NED course
0   1   Hamza                 AI
1   2    Asif  DataVisualization
2   3  Junaid                 DS

0                   AI
1    DataVisualization
2                   DS
Name: NED course, dtype: object

In [25]:
df.Timing = '1PM to 3PM' # add new column

df

id    name         NED course
0   1   Hamza                 AI
1   2    Asif  DataVisualization
2   3  Junaid                 DS

In [27]:
df['Timing'] = "1 PM to 3PM"
df

id    name         NED course       Timing
0   1   Hamza                 AI  1 PM to 3PM
1   2    Asif  DataVisualization  1 PM to 3PM
2   3  Junaid                 DS  1 PM to 3PM

In [28]:
df.values

array([[1, 'Hamza', 'AI', '1 PM to 3PM'],
       [2, 'Asif', 'DataVisualization', '1 PM to 3PM'],
       [3, 'Junaid', 'DS', '1 PM to 3PM']], dtype=object)

In [29]:
df.columns

Index(['id', 'name', 'NED course', 'Timing'], dtype='object')

In [30]:
df.index

RangeIndex(start=0, stop=3, step=1)

extrace more than one columns

dataframe[list_of_columns]

In [31]:
df.columns


Index(['id', 'name', 'NED course', 'Timing'], dtype='object')

In [32]:
df[['Timing','id','name']]


Timing  id    name
0  1 PM to 3PM   1   Hamza
1  1 PM to 3PM   2    Asif
2  1 PM to 3PM   3  Junaid

In [33]:
cols = ['Timing','id','name']
df[cols]

Timing  id    name
0  1 PM to 3PM   1   Hamza
1  1 PM to 3PM   2    Asif
2  1 PM to 3PM   3  Junaid

In [34]:
s1 = df.id
type(s1)

pandas.core.series.Series

In [35]:
s1 = df['id']
type(s1)

pandas.core.series.Series

In [36]:
s1 = df[['id']]
type(s1)

pandas.core.frame.DataFrame

In [38]:
df

id    name         NED course       Timing
0   1   Hamza                 AI  1 PM to 3PM
1   2    Asif  DataVisualization  1 PM to 3PM
2   3  Junaid                 DS  1 PM to 3PM

In [37]:
df1=pd.DataFrame(
    {"roll no":np.arange(1,101),
     'name':np.random.choice(['Ali','Hamza','Junaid',"Asif"],100),
     'fname':np.random.choice(['Ali','Hamza','Junaid',"Asif"],100),
     'course':np.random.choice(['AI','DS','ML',"Blockchain"],100),
     's1':np.random.randint(1,100,100),
     's2':np.random.randint(1,100,100),
     's3':np.random.randint(1,100,100),
     's4':np.random.randint(1,100,100),
     's5':np.random.randint(1,100,100),}
)
df1

roll no    name   fname      course  s1  s2  s3  s4  s5
0         1   Hamza    Asif          AI  93   2  43  82  29
1         2   Hamza   Hamza          DS  48  40  23  59  30
2         3  Junaid  Junaid          ML  94  29  65   4  45
3         4    Asif    Asif  Blockchain  75  21  67  17  22
4         5   Hamza  Junaid          AI  41  19  35   7  95
..      ...     ...     ...         ...  ..  ..  ..  ..  ..
95       96     Ali   Hamza  Blockchain  55  14  28  87  83
96       97  Junaid   Hamza          AI  72   2   8  66  32
97       98   Hamza   Hamza          AI  77  96  57  16  55
98       99   Hamza   Hamza          AI  50  78  87  54  52
99      100    Asif  Junaid          ML  61  18  74  32  95

[100 rows x 9 columns]